### ISSUE TITLE
初始化启动就报错

### ISSUE THREAD

**Issue by jackTang11** [alibaba/power_image#10]
`
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/foundation/binding.dart': Failed assertion: line 55 pos 12: '!_debugInitialized': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      new BindingBase (package:flutter/src/foundation/binding.dart:55:12)
#3      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
#4      new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
#5      new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
#6      new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
#7      new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&P<…>
`

`
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/Documents/work/softwork/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • FA12CED7-A7E5-4978-8DA3-203FE47AEDA9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 102.0.5005.61

`

**Comment by jackTang11** [comment]
ios 端

**Comment by wongkoo** [comment]
贴一下 dart 侧初始化代码 @jackTang11

**Comment by jackTang11** [comment]
> 贴一下 dart 侧初始化代码 @jackTang11

`
    ///添加初始化
    PowerImageBinding();
    ///添加全局power_image的加载方式
    PowerImageLoader.instance.setup(PowerImageSetupOptions(renderingTypeTexture,
        errorCallbackSamplingRate: null,
        errorCallback: (PowerImageLoadException exception) {}));
`

**Comment by ManInTheWind** [comment]
> > 贴一下 dart 侧初始化代码 @jackTang11
> 
> `///添加初始化 PowerImageBinding(); ///添加全局power_image的加载方式 PowerImageLoader.instance.setup(PowerImageSetupOptions(renderingTypeTexture, errorCallbackSamplingRate: null, errorCallback: (PowerImageLoadException exception) {}));`

 PowerImageBinding需要在WidgetsFlutterBinding初始化前加入，如果有写到WidgetsFlutterBinding.ensureInitialized()等的初始化动作，那么需要把 PowerImageBinding()放在WidgetsFlutterBinding.ensureInitialized()之前，
