### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Livjxbill993** [alibaba/power_image#15]
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Include of non-modular header inside framework module 'SDWebImage.SDWebImage': '/Users/1/AndroidStudioProjects/kaimeid_app/ios/Pods/Headers/Public/SDWebImage/SDWebImageCompat.h'
/Users/1/AndroidStudioProjects/kaimeid_app/ios/Pods/SDWebImage/WebImage/SDWebImage.h:9:8

更多这样的提示

谢谢🙏

**Comment by wongkoo** [comment]
请先试一下 example_kotlin_swift 中是否正常。
