### ISSUE TITLE
使用 RepaintBoundary  生成图片失败

### ISSUE THREAD

**Issue by peak77** [alibaba/power_image#16]
``` 
RepaintBoundary(
  key: _screenshotKey,
  child: PowerImage.network(
    'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg',
    renderingType: renderingTypeTexture,
  ),
)
```

**Comment by wongkoo** [comment]
`renderingTypeTexture `使用了`Texture Widget`，无法生成图片。
将`renderingType`换成`renderingTypeExternal`即可。

相关 flutter 问题：https://github.com/flutter/flutter/issues/63265

**Comment by peak77** [comment]
看了公众号的文章的集中加载图片的数据对比和滚动流畅分析，使用  ` renderingTypeExternal ` 性能不太好~
