### ISSUE TITLE
 PowerImageLoader for network has not been registered.

### ISSUE THREAD

**Issue by leetomlee123** [alibaba/power_image#22]
E/MethodChannel#power_image/method(26251): Failed to handle method call
E/MethodChannel#power_image/method(26251): java.lang.IllegalStateException: PowerImageLoader for network has not been registered.
E/MethodChannel#power_image/method(26251): 	at com.taobao.power_image.loader.PowerImageLoader.handleRequest(PowerImageLoader.java:35)
E/MethodChannel#power_image/method(26251): 	at com.taobao.power_image.request.PowerImageBaseRequest.performLoadImage(PowerImageBaseRequest.java:60)
E/MethodChannel#power_image/method(26251): 	at com.taobao.power_image.request.PowerImageBaseRequest.startLoading(PowerImageBaseRequest.java:55)
E/MethodChannel#power_image/method(26251): 	at com.taobao.power_image.request.PowerImageRequestManager.startLoadingWithArguments(PowerImageRequestManager.java:71)

**Comment by wongkoo** [comment]
相似问题：https://github.com/alibaba/power_image/issues/4
