### ISSUE TITLE
Demo运行成功，但集成进原有项目中，原生方法中PowerImageLoaderProtocol中的协议方法也执行了，但Flutter中图片未成功显示，有可能是哪个环节出了问题

### ISSUE THREAD

**Issue by Mr-Yao07** [alibaba/power_image#26]

**Comment by wanhongbo** [comment]
也遇到类似的问题，原有项目没有使用FlutterBoost，而是使用EngineGroup，是否跟这个有关？

**Comment by wongkoo** [comment]
可以尝试下将  `renderingType`换成`renderingTypeExternal`

**Comment by Mr-Yao07** [comment]
> 可以尝试下将 `renderingType`换成`renderingTypeExternal`

将 renderingTypeTexture 换成 renderingTypeExternal 的确有用，问题已解决。renderingTypeTexture 这种方式目前个人的理解是与咸鱼博客文章所说的外接纹理吻合的，renderingTypeExternal 这种加载方式又是怎样的，它们的主要区别方便大致说一下吗，感谢
