### ISSUE TITLE
像这种分辨率超级大的图片加载不出来啊，内存也相当的高。

### ISSUE THREAD

**Issue by wangyuuuu** [alibaba/power_image#29]
可以再demo里试下这四张：
  PowerImage.network('https://img.zai-art.com/zaiart/saas/image/bf9ec3d1a68e11487e0ae364e47b5593.jpg'),
  PowerImage.network('https://img.zai-art.com/zaiart/saas/image/affb80135bf5b942573617e37e56bb5b.jpg'),
  PowerImage.network('https://img.zai-art.com/zaiart/saas/image/90cf1707fae19c9427c3a824fe4ed2df.jpg'),
  PowerImage.network('https://img.zai-art.com/zaiart/saas/image/70fd6c0530a055af442a1602a212afe1.jpg'),

**Comment by wangyuuuu** [comment]
renderingTypeExternal 可以正常加载，4张图片内存就867m了

**Comment by wongkoo** [comment]
你好，你预期是加载原图还是某个尺寸的图呢，我看你没有指定图片的尺寸。安卓因为纹理过大会crash，所以会有限制，iOS则没有。
一般情况下需要自定义loader进行图片尺寸的处理，加载什么尺寸的图完全是自定义的。

**Comment by wangyuuuu** [comment]
您好，我是王宇，你的邮件我已收到，我将尽快给您回复。

**Comment by wangyuuuu** [comment]
PowerImage.network('https://img.zai-art.com/zaiart/saas/image/bf9ec3d1a68e11487e0ae364e47b5593.jpg',width: 200,height: 200,imageHeight: 200,imageWidth: 200,),
        PowerImage.network('https://img.zai-art.com/zaiart/saas/image/affb80135bf5b942573617e37e56bb5b.jpg',width: 200,height: 200,imageHeight: 200,imageWidth: 200,),
        PowerImage.network('https://img.zai-art.com/zaiart/saas/image/90cf1707fae19c9427c3a824fe4ed2df.jpg',width: 200,height: 200,imageHeight: 200,imageWidth: 200,),
        PowerImage.network('https://img.zai-art.com/zaiart/saas/image/70fd6c0530a055af442a1602a212afe1.jpg',width: 200,height: 200,imageHeight: 200,imageWidth: 200,),


这也没用啊，内存还是很大。怎么能把内存降下来啊

**Comment by wongkoo** [comment]
在网络图对应的 loader 中把加载的图片压缩成想要尺寸的小图，再回调给PowerImage。

https://github.com/alibaba/power_image/blob/7587cd4877d4e5f6465016a70a309e74f6a45485/example/ios/Runner/Biz/PowerImageNetworkImageLoader.m#L19

比如这个尺寸，就是flutter侧给到 PowerImage的imageHeight、imageWidget，正常情况下需要把加载的图压缩成这个尺寸。

**Comment by jackTang11** [comment]
果然如此,已经很久没有更新了,以前听说ali出来一个框架,后续基本上不做维护,现在看来是真的

**Comment by wangyuuuu** [comment]
您好，我是王宇，你的邮件我已收到，我将尽快给您回复。

**Comment by wongkoo** [comment]
> 果然如此,已经很久没有更新了,以前听说ali出来一个框架,后续基本上不做维护,现在看来是真的


不会的，至少只要我还在，肯定一直维护 ：）

毕竟闲鱼在全量使用，因为现在需要工作中抽时间维护，所以进展比较慢。
