### ISSUE TITLE
external模式下不支持动图

### ISSUE THREAD

**Issue by long8313002** [alibaba/power_image#31]
项目切换到renderingTypeExternal模式，但是gif动图只能显示第一帧

**Comment by wongkoo** [comment]
是的，目前只有 texture 支持动图，external 暂时不支持。
不过因为 PowerImage 与系统图片共用 ImageCache，所以对于动图也可以使用原生图片。

**Comment by long8313002** [comment]
你的意思是使用 PlatformView 吗？
