### ISSUE TITLE
PowerImage rotating images

### ISSUE THREAD

**Issue by Gastrolize** [alibaba/power_image#37]
**Describe the bug**
When using Power Image the Image gets displayed rotated.
I also checked the Image on my computer and it opens in expected format, also in browser. Just not with power image.
I tried PowerImage.network and PowerImage.file:

PowerImage.file(widget.file!.path,fit: BoxFit.fitHeight, renderingType: renderingTypeExternal,errorBuilder: (_,__,___) => ErrorStoryWidget()))

**Screenshots**

**Versions (please complete the following information):**
 - Device: [Iphone 12 Pro Max]
 - OS: [Ios 16]
 - `flutter doctor -v`:
 [✓] Flutter (Channel stable, 3.0.4, on macOS 12.6 21G115 darwin-x64, locale de-DE)
    • Flutter version 3.0.4 at /Users/sobhihammoud/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sobhihammoud/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/sobhihammoud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Users/sobhihammoud/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Users/sobhihammoud/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7442.40/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554             • android-x64    • Android 13 (API 33) (emulator)
    • iPhoneS (mobile)             • 00008101-001E4DA20A29003A • ios            • iOS 16.0 20A362
    • iPad von Sobhi (2) (mobile)  • 00008027-001550490131802E • ios            • iOS 15.5 19F77
    • macOS (desktop)              • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

 - power_image Version: ^0.1.0-pre.2
 - power_image_ext Version: 2.5.3

**Additional context**
Attaching Screenshots
![IMG_6343](https://user-images.githubusercontent.com/72274345/194643568-5f2a2de2-3be9-4e03-a46b-211294646bdc.PNG)
![IMG_6344](https://user-images.githubusercontent.com/72274345/194643573-19ad16c9-810a-4f0b-866b-69cc360fda3a.PNG)
![354c81b8-e394-4cfc-a1db-106399dc411e](https://user-images.githubusercontent.com/72274345/194643646-f46fc457-87bc-49ee-8219-f3a29c55cce9.jpg)

![6b5dc37f-41f3-4b13-a783-b2e1ffeac4c4](https://user-images.githubusercontent.com/72274345/194643587-23f434b5-49f5-4a12-85e8-796f1cef27ed.jpg)

**Comment by Gastrolize** [comment]
I am sorry, i noticed that the backend server by compressing images changes the rotation flag in the image. Weird but power image working fine, sorry guys!

**Comment by yangha886** [comment]
歪果仁不用聊天工具的嘛
