### ISSUE TITLE
flutter 3.7.0 网络图片  renderingTypeTexture  Texture descriptor was invalid.  renderingTypeExternal  图片变形

### ISSUE THREAD

**Issue by zhanglexiaoge** [alibaba/power_image#43]
![截屏2023-02-24 15 54 11](https://user-images.githubusercontent.com/16223789/221123141-8a4e4eed-e73c-4d27-b090-12de35e1d641.png)
![截屏2023-02-24 15 54 48](https://user-images.githubusercontent.com/16223789/221123345-365b99b4-0610-49a8-a337-4abfe05291b9.png)
renderingTypeTexture Texture descriptor was invalid.

**Comment by zhanglexiaoge** [comment]
和官方这个报错 一样 
https://github.com/flutter/flutter/issues/119818
只是升级到3.7.3 还是有同样错误

**Comment by zhanglexiaoge** [comment]
接入是错误导致

**Comment by yangha886** [comment]
Impeller关了就好了
