### ISSUE TITLE
支持base64吗？后台返回的是base64啊，怎么展示呢

### ISSUE THREAD

**Issue by choubaguai** [alibaba/power_image#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - `flutter doctor -v`:
 - power_image Version: [e.g. 0.1.0]
 - power_image_ext Version: [e.g. 2.5.3]

**Additional context**

**Comment by wongkoo** [comment]
在 iOS 端，PowerImage 要的只是 UIImage，你只需要将 base64 转成 UIImage，那么一定是支持展示的。

**Comment by wongkoo** [comment]
base64 在 flutter 侧可以直接转，不需要使用 PowerImage
