### ISSUE TITLE
there's something wrong with the picture's fit.

### ISSUE THREAD

**Issue by lexoops** [alibaba/power_image#46]
**Describe the bug**
i wanna make the image full  in sized of container but it's show me that just like the screenshot i put.i don't know why?when i set BoxFit.cover or  BoxFit.contain to it i still  get same situations...please help

**To Reproduce**
`     icon:Container(
          decoration: BoxDecoration(borderRadius: BorderRadius.circular(5),border: Border.all(color: colorScheme.onTertiary,width: 1),),
          child: v2timFriendInfo.userProfile!.faceUrl!.isNotEmpty? Container(
            decoration: BoxDecoration(borderRadius: BorderRadius.circular(8),color: Colors.transparent),
            clipBehavior: Clip.antiAlias,
            child: PowerImage.network("${v2timFriendInfo.userProfile!.faceUrl}",width: widget.size??48,height: widget.size??48,fit: BoxFit.cover),
          )
              :PowerImage.asset("assets/images/mine/user.png",width: widget.size??48,height: widget.size??48,renderingType:renderingTypeExternal),
        ),`

**Expected behavior**
picture can full of in the container

**Screenshots**
![image](https://user-images.githubusercontent.com/33716494/230710487-714dd74a-e2d0-4c19-889e-17560a3ccb38.png)
![image](https://user-images.githubusercontent.com/33716494/230710817-a5e3f316-00eb-4660-ac44-d0c921e01cc1.png)
![image](https://user-images.githubusercontent.com/33716494/230710848-b4736c32-9b63-4f82-9cc0-43a9e5b59dd0.png)

**Versions (please complete the following information):**
 - Device: [android nox simulator]
 - `flutter doctor -v`:
 -   power_image: 0.1.0-pre.2
 - power_image_ext: 3.0.0

**Additional context**

**Comment by wongkoo** [comment]
Obviously, the first picture in the illustration has white borders on the left and right, which is not a bug of PowerImage.
