### ISSUE TITLE
libpowerimage.so C 模块的代码有计划开源出来么？

### ISSUE THREAD

**Issue by wevendex** [alibaba/power_image#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - `flutter doctor -v`:
 - power_image Version: [e.g. 0.1.0]
 - power_image_ext Version: [e.g. 2.5.3]

**Additional context**

**Comment by ksballetba** [comment]
目前C++ 代码就在本项目里面，
https://github.com/alibaba/power_image/blob/main/android/src/main/cpp/external_image_jni.cpp
libpowerimage.so 就是这个的编译产物
